import {
  type RouteConfig,
  index,
  route,
} from "@react-router/dev/routes";

export default [
  index("routes/landing.tsx"),
  route("login", "routes/login.tsx"),
  route("forgot-password", "routes/forgot-password.tsx"),
  route("reset-password", "routes/reset-password.tsx"),
  route("verify-email", "routes/verify-email.tsx"),
  route("two-factor", "routes/two-factor.tsx"),
  route("register", "routes/register.tsx"),
  route("r/:referralCode", "routes/r.$referralCode.tsx"),
  route("api/auth/*", "routes/api.auth.$.ts"),
  route("api/messages/:tradeId", "routes/api.messages.$tradeId.ts"),
  route("api/chat-stream/:tradeId", "routes/api.chat-stream.$tradeId.ts"),
  route("api/chat", "routes/api.chat.ts"),
  route("api/support/chat", "routes/api.support.chat.ts"),
  route("api/pay/upgrade", "routes/api.pay.upgrade.ts"),
  route("api/pay/webhook", "routes/api.pay.webhook.ts"),
  route("api/pay/cancel", "routes/api.pay.cancel.ts"),
  route("api/refer", "routes/api.refer.ts"),
  route("api/refer/complete", "routes/api.refer.complete.ts"),
  route("api/upload", "routes/api.upload.ts"),
  route("api/push-subscribe", "routes/api.push-subscribe.ts"),
  route("api/device-fingerprint", "routes/api.device-fingerprint.ts"),
  route("api/device-verify", "routes/api.device-verify.ts"),
  route("api/test-email", "routes/api.test-email.ts"),
  route("dashboard", "routes/dashboard.tsx", [
    index("routes/dashboard/home.tsx"),
    route("asset/:id", "routes/dashboard/asset.$id.tsx"),
    route("pings", "routes/dashboard/pings.tsx"),
    route("pings/:id", "routes/dashboard/pings.$id.tsx"),
    route("notifications", "routes/dashboard/notifications.tsx"),
    route("map", "routes/dashboard/map.tsx"),
    route("add", "routes/dashboard/add.tsx"),
    route("trade/:id", "routes/dashboard/trade.$id.tsx"),
    route("chat/:tradeId", "routes/dashboard/chat.$tradeId.tsx"),
    route("profile", "routes/dashboard/profile.tsx"),
    route("billing", "routes/dashboard/billing.tsx"),
    route("verify-phone", "routes/dashboard/verify-phone.tsx"),
    route("refer", "routes/refer.tsx"),
    route("settings/security", "routes/dashboard/settings-security.tsx"),
  ]),
  route("legal", "routes/legal.tsx", [
    route("terms", "routes/legal/terms.tsx"),
    route("privacy", "routes/legal/privacy.tsx"),
    route("community-guidelines", "routes/legal/community-guidelines.tsx"),
    route("complaints", "routes/legal/complaints.tsx"),
    route("beta-promo", "routes/legal/beta-promo.tsx"),
  ]),
  // Catch-all: renders 404 for any unmatched URL
  route("*", "routes/$.tsx"),
] satisfies RouteConfig;
